# Generated by Django 5.2.16 on 2026-07-24 19:01

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default=accounts.models.default_country, max_length=100),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=accounts.models.default_commission_rate, help_text='Platform commission percentage.', max_digits=5),
        ),
    ]
