# Generated by Django 5.2.16 on 2026-07-25 14:43

import billing.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_address_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.DateField(help_text='First day of the billed month.')),
                ('amount', models.DecimalField(decimal_places=2, default=billing.models.default_monthly_fee, help_text='Snapshotted at generation; changing the platform fee never rewrites an issued invoice.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('due', 'Due'), ('submitted', 'Payment submitted'), ('paid', 'Paid'), ('waived', 'Waived')], db_index=True, default='due', max_length=12)),
                ('due_date', models.DateField()),
                ('payment_reference', models.CharField(blank=True, help_text='Transfer reference the seller quoted.', max_length=120)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_invoices', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounts.sellerprofile')),
            ],
            options={
                'db_table': 'billing_invoice',
                'ordering': ['-period', 'seller__shop_name'],
                'indexes': [models.Index(fields=['seller', '-period'], name='billing_inv_seller__e87aeb_idx'), models.Index(fields=['status', 'due_date'], name='billing_inv_status_996e80_idx')],
                'constraints': [models.UniqueConstraint(fields=('seller', 'period'), name='uniq_invoice_seller_period')],
            },
        ),
    ]
