#!/usr/bin/env bash
# Build step for a hosted deploy (Render runs this as its Build Command).
#
# `set -o errexit` matters more than it looks: without it a failed migration
# still exits 0, the service starts, and you get 500s against a half-migrated
# database instead of a failed deploy you can actually see.
set -o errexit
set -o pipefail
set -o nounset

cd "$(cd "$(dirname "$0")" && pwd -P)"

pip install --upgrade pip
pip install -r requirements.txt

# --no-input so it can never block waiting for a prompt no one will answer.
python manage.py collectstatic --no-input

# Migrations run at build, not at start. A web service can boot more than one
# worker, and concurrent `migrate` calls race each other.
python manage.py migrate --no-input

# Optional demo data, controlled by an env var so production deploys don't get
# a fake catalogue. Images are generated by Pillow at seed time rather than
# committed, so this also repopulates media after the ephemeral disk is wiped.
if [ "${SEED_DEMO:-false}" = "true" ]; then
  echo "SEED_DEMO=true — populating the demo catalogue"
  python manage.py seed_demo
fi
