# Generated by Django 5.2.16 on 2026-07-25 14:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_address_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('audience', models.CharField(choices=[('all', 'All sellers'), ('selected', 'Selected sellers')], default='selected', max_length=10)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notices_admin_notice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoticeRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='notices.adminnotice')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='accounts.sellerprofile')),
            ],
            options={
                'db_table': 'notices_notice_recipient',
                'ordering': ['-notice__created_at'],
                'indexes': [models.Index(fields=['seller', 'read_at'], name='notices_not_seller__2fee6b_idx')],
                'constraints': [models.UniqueConstraint(fields=('notice', 'seller'), name='uniq_notice_recipient')],
            },
        ),
    ]
